import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


def _markdown_to_html(text: str) -> str:
    """Minimal markdown → HTML for email rendering."""
    import re
    # Headers
    text = re.sub(r"^## (.+)$", r"<h2>\1</h2>", text, flags=re.MULTILINE)
    text = re.sub(r"^### (.+)$", r"<h3>\1</h3>", text, flags=re.MULTILINE)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Bullet points
    text = re.sub(r"^- (.+)$", r"<li>\1</li>", text, flags=re.MULTILINE)
    text = re.sub(r"(<li>.*</li>)", r"<ul>\1</ul>", text, flags=re.DOTALL)
    # Line breaks
    text = text.replace("\n\n", "</p><p>")
    return f"<p>{text}</p>"


def send_email(
    subject: str,
    body_markdown: str,
    recipient: str,
    sender_email: str,
    sender_password: str,
    smtp_host: str = "smtp.gmail.com",
    smtp_port: int = 587,
) -> None:
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender_email
    msg["To"] = recipient

    html_body = f"""
    <html>
    <head>
    <style>
        body {{ font-family: Georgia, serif; max-width: 700px; margin: 40px auto; color: #1a1a1a; line-height: 1.7; }}
        h1 {{ color: #0a2540; border-bottom: 2px solid #0a2540; padding-bottom: 8px; }}
        h2 {{ color: #0a2540; margin-top: 28px; }}
        h3 {{ color: #444; }}
        li {{ margin-bottom: 6px; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 12px; }}
        .badge {{ background: #0a2540; color: white; padding: 2px 8px; border-radius: 3px; font-size: 12px; }}
    </style>
    </head>
    <body>
    <h1>{subject}</h1>
    {_markdown_to_html(body_markdown)}
    <div class="footer">
        Generated by Leo Watch · {datetime.utcnow().strftime("%B %d, %Y")} ·
        <a href="https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0002045724&type=13F-HR">
        Situational Awareness LP SEC Filings</a>
    </div>
    </body>
    </html>
    """

    msg.attach(MIMEText(body_markdown, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient, msg.as_string())

    print(f"Email sent to {recipient}: {subject}")
